### ISSUE TITLE
Issue with textIndent

### ISSUE THREAD

**Issue by melloware** [microneer/jquery.tabSlideOut.js#1]
Hey great job on this component it fit our needs exactly.  However we did find 1 issue.  We are NOT using an image for our tab but instead text.   Your current code will not display text in the tab.  See this JSFiddle below.

http://jsfiddle.net/grqxq591/4/

I have this line commented out and everything works:
`//'textIndent' : '-99999px',`

If you uncomment that line and re-execute it you will see the word "Feedback" no longer appears on the tab.  Other than that the component works like a charm.

**Comment by microneer** [comment]
Thanks! Fixed in f2dd0cede4778597a03008db380ceb1d66653802.
