### ISSUE TITLE
Scrollbars for Height Overflow

### ISSUE THREAD

**Issue by jkomar** [microneer/jquery.tabSlideOut.js#12]
Has anyone figured out a way to display scrollbars on the panel div when the content overflows the height? I have been trying for hours to figure out a way to make this happen and I am out of ideas of what to try.

Thanks,
Jason

**Comment by microneer** [comment]
I think I figured out how to do it. I updated readme.md with an explanation and link to the new JSFiddle which demonstrates it. See https://github.com/microneer/jquery.tabSlideOut.js/commit/d17dd5a19e30cfc973c002e7a465985545f8413d. 

Does it do what you want?

**Comment by melloware** [comment]
@microneer nice work as always looks good to me!

**Comment by jkomar** [comment]
Does exactly what I needed.

Thanks!
