### ISSUE TITLE
How to add multiple tab in same position

### ISSUE THREAD

**Issue by bdthemes** [microneer/jquery.tabSlideOut.js#13]
Please take a look here: http://demo.accesspressthemes.com/wordpress-plugins/easy-side-tab-pro/demo/

**Comment by melloware** [comment]
Are you asking how to make this component look exactly like that one you posted with multiple "buttons" on the tab?

**Comment by bdthemes** [comment]
Yeah, I need multiple button like as that example, is it possible?

**Comment by melloware** [comment]
I will let @microneer answer that. I just wanted to clarify that is what you were asking.

**Comment by microneer** [comment]
Your options, I believe: 
1. You can put all your icons in one tab. When any of it is clicked, the (one) panel will open and all the tab icons will move together.
1. Alternatively, you could create multiple tabs, carefully placed next to each other using jquery.tabSlideOut.js, and fix the size of each tab with CSS. That way you get independent panels for each tab.
1. Finally, if you want it exactly like that plugin... erm, I guess you could buy the plugin?
