### ISSUE TITLE
Push option

### ISSUE THREAD

**Issue by simon1tan** [microneer/jquery.tabSlideOut.js#14]
Really like plugin and I have looked at almost 20 trying to find a good one. 

Please add a "push" option. Basically, the tab "pushes" the page contents instead of sliding over the content. Thanks.

**Comment by melloware** [comment]
Not sure this is the right component for that as its meant as an "overlay".   I know what you are trying to achieve just not sure this is the correct component.

You want something like this: https://www.primefaces.org/babylon/

In that Demo when you close and open the "burger" menu it pushes all of the content to the right etc.  Is that an example of what you want?

**Comment by microneer** [comment]
I think achieving that would require a different page structure. Firstly
the current library leaves a margin (although it can be set to zero) around
the slide out panel, which is not something you would want if the rest of
the page slid out the way. Secondly, the current tabs and panels sit inside
the main content - to achieve the push technique, they would be best as
peers of the main content, and some way of holding any other tabs so they
don't get pushed would be required?

Not saying it can't be done or isn't a great idea, but unless there's a
pull request, it's not something I will work on, sorry.
