### ISSUE TITLE
new events

### ISSUE THREAD

**Issue by simon1tan** [microneer/jquery.tabSlideOut.js#15]
New events onBeforeOpen and onBeforeClose would be nice in case we want to cancel or do something else.

**Comment by microneer** [comment]
Easy to do, added to fbb989430b1dd97db5f6286bcafb428518c2ad0c and released as [v2.5](https://github.com/microneer/jquery.tabSlideOut.js/tree/2.5).

**Comment by melloware** [comment]
@microneer nice work!  One minor thing you forgot to bump the version at the top of the file it still says 2.4.

**Comment by microneer** [comment]
Indeed, and I mis-named the release "2.5" instead of "v2.5". Re-released with those things corrected, thanks for pointing it out!
