### ISSUE TITLE
Spacing when position on right

### ISSUE THREAD

**Issue by melloware** [microneer/jquery.tabSlideOut.js#2]
I am having trouble getting the tab to actually line up with the panel when positioned on the right.  See this JSFiddle for an example.

http://jsfiddle.net/grqxq591/12/

When you click the tab you will see it is floating away from the body.  Any thoughts?

**Comment by microneer** [comment]
One way to fix this is use the css transform-origin property.

A better way is to use a CSS translate after the rotate transform. http://www.w3schools.com/cssref/css3_pr_transform.asp

I'm just making a CSS file to go with this plugin which takes care of all that. Watch this space for v2.2.

**Comment by microneer** [comment]
FYI the 'open' css class is added when the tab is open, so you don't need to use the onOpen and onClose handlers as you are doing in that JSFiddle.

**Comment by melloware** [comment]
Awesome. I am now really looking forward to your 2.2!  Any timeline for that?

A few things...
1.  I see the "open" style is added to the main Div but not the handle?  I was styling the just the handle.  Although I guess my style could be clever to now to look for any span inside the "open" etc.
2. Would a better name be "ui-slideouttab-open" to be more consistent?  And actually to add a CSS stylre to the handle as well in case people want to style each individually?
3. I was also thinking to be able to Jquery ThemeRoller style the component as well similar to how Qtip2 offers custom styling or ThemeRoller styling. Thoughts?
4.  I am a committer on Primefaces Extensions a JSF component library and I plan on making a TabSlideOut JSF component based on this plugin if that is OK? http://primefaces-extensions.github.io/

**Comment by microneer** [comment]
1. Try the new commit 11db5204f6662b6afd0cac32d8bf97f947d1c03d which comes with a CSS file and should produce properly rotated tab handles. There is a demo, I just have to figure out how to get it into JSFiddle and then update the readme. The demo also shows how to put Font Awesome icons into tab handles.
2. I think it's better to just put 'open' on the parent element.
3. Good idea, done.
4. I wouldn't have a clue how to do it, but happy to take a pull request :-)
5. Great! I think you'll find this latest commit is a lot more capable too.

**Comment by melloware** [comment]
OK I will look into ThemeRoller support!  And the FontAwesome stuff is a nice touch!

I will checkout your latest changes and let you know how it goes.  Once again much props for this component!

**Comment by microneer** [comment]
I've added the ability to register event handlers for open, etc.

The demo works and is now linked in the readme. I had to [raise an issue for JSFiddle](https://github.com/jsfiddle/jsfiddle-issues/issues/895).
