### ISSUE TITLE
Improvement request

### ISSUE THREAD

**Issue by sirlordt** [microneer/jquery.tabSlideOut.js#9]
Hi! Thanks for this excelent plugin. But i suggest a improvement.

Multi tabs in single set, the next links a example from this feacture.

http://www.jqueryscript.net/other/Minimal-Drawer-Sidebar-Plugin-with-jQuery-Sidebar-js.html
http://www.jqueryscript.net/demo/Minimal-Drawer-Sidebar-Plugin-with-jQuery-Sidebar-js/

Can you implement this please?

**Comment by microneer** [comment]
Hi, it's an interesting suggestion. You could achieve something similar-ish by having the panels overlaying each other. Happy to take a pull request for the feature but it's not something I'll develop myself, sorry.
